/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vendas;

import java.beans.PropertyVetoException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Pichau
 */
public class AlterarVendasInternalFrame extends javax.swing.JInternalFrame {

    private final Connection conn;
    private int quantidadeInicial;
    /**
     * Creates new form AlterarVendasInternalFrame
     * @param conn
     */
    public AlterarVendasInternalFrame(Connection conn) {
        initComponents();
        this.conn = conn;
        populaDados(conn);
    }

        
            /**
     * Método que seleciona os Produtos e popula a Interface
     * @param conn 
     */
     public void populaDados (Connection conn) {
        
        String sql = "SELECT codigo "
                     + "FROM venda;";
        
        try {
            
            Statement comandoSql = conn.createStatement();
            
            ResultSet rs  = comandoSql.executeQuery(sql);
                      
            while(rs.next()) {
                jComboBoxVenda.addItem(rs.getString("codigo"));
            }
            
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }  
    }
    
     public void atualizaSelecao (Connection conn,int cod) {
         
         String sql = "SELECT * "
                     + "FROM venda WHERE codigo = ?;";
        
        try {
            
            PreparedStatement pstmt = conn.prepareStatement(sql); 
                
            pstmt.setInt(1, cod);
            
            ResultSet rs  = pstmt.executeQuery();
            
            if (rs != null){
                jLabelProduto.setText(rs.getString("id_produto"));
                jLabelFornecedor.setText(rs.getString("fornecedor"));
                jTextFieldQuantidade.setText(Integer.toString(rs.getInt("quantidade")));
                quantidadeInicial = rs.getInt("quantidade");
            }           
            
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }  
     }
     
              /**
      * Método que atualiza Produtos no Banco de Dados
      * @param conn
     * @param cod 
      */
     public void atualizaVenda (Connection conn,int cod) {
        String sql = "UPDATE venda SET quantidade = ?  WHERE codigo = ?";
 
        try {
                PreparedStatement pstmt = conn.prepareStatement(sql); 
                
                pstmt.setInt(1, Integer.parseInt(jTextFieldQuantidade.getText()));
                pstmt.setInt(2, cod);
                
                pstmt.executeUpdate();
                
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
    }
     
    public void atualizaProduto (Connection conn,int cod,int qtd) {
        String sql = "UPDATE produto SET quantidade = quantidade + ?  WHERE codigo = ?";
 
        try {
                PreparedStatement pstmt = conn.prepareStatement(sql); 
                
                pstmt.setInt(1, qtd);
                pstmt.setInt(2, cod);
                
                pstmt.executeUpdate();
                
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
    }

    public void mensagem (String mensagem) {
        JOptionPane.showMessageDialog(null,mensagem);
    } 
        
    public void close(){
        try {
                this.setClosed(true);
                } catch (PropertyVetoException ex) {
                    System.err.println("Closing Exception");
            }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldQuantidade = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBoxVenda = new javax.swing.JComboBox<>();
        jButtonAlterar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabelFornecedor = new javax.swing.JLabel();
        jLabelProduto = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Alterar Venda");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Quantidade:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Código:");

        jComboBoxVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxVendaActionPerformed(evt);
            }
        });

        jButtonAlterar.setText("Alterar");
        jButtonAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAlterarActionPerformed(evt);
            }
        });

        jLabel4.setText("Produto:");

        jLabel5.setText("Fornecedor:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addComponent(jButtonAlterar))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(75, 75, 75)
                                .addComponent(jLabelFornecedor))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(96, 96, 96)
                                .addComponent(jLabelProduto))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(34, 34, 34)
                                .addComponent(jComboBoxVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(145, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBoxVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabelProduto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabelFornecedor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                .addComponent(jButtonAlterar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlterarActionPerformed
        // TODO add your handling code here:
        int cod = Integer.parseInt(jComboBoxVenda.getSelectedItem().toString());
        int codProduto = Integer.parseInt(jLabelProduto.getText());
        int quantidade = Integer.parseInt(jTextFieldQuantidade.getText());
        if (quantidade <= quantidadeInicial) {
            atualizaProduto(conn,codProduto,(quantidadeInicial - quantidade));
            atualizaVenda(conn,cod);
            mensagem("Venda Atualizada.");
            close();
        }
        
    }//GEN-LAST:event_jButtonAlterarActionPerformed

    private void jComboBoxVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxVendaActionPerformed
        // TODO add your handling code here:
        int cod = Integer.parseInt(jComboBoxVenda.getSelectedItem().toString());
        atualizaSelecao(conn,cod);
    }//GEN-LAST:event_jComboBoxVendaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAlterar;
    private javax.swing.JComboBox<String> jComboBoxVenda;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelFornecedor;
    private javax.swing.JLabel jLabelProduto;
    private javax.swing.JTextField jTextFieldQuantidade;
    // End of variables declaration//GEN-END:variables
}
