/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Relatorios;

import Vendas.Venda;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author juanfelipevillalba
 */
public class RelatoriosVendasInternalFrame extends javax.swing.JInternalFrame {

    private final Connection conn;

    /**
     * Creates new form RelatoriosVendasInternalFrame
     * @param conn
     */
    public RelatoriosVendasInternalFrame(Connection conn) {
        initComponents();
        this.conn = conn;
        showJTable();
    }
    
        public ArrayList<Venda> getVendasList(Connection conn) {
        ArrayList<Venda> listaVendas = new ArrayList<>();
        
        String sql = "SELECT * FROM venda";

        
        try {
            
            Statement comandoSql = conn.createStatement();
            ResultSet rs  = comandoSql.executeQuery(sql);
            
            
            while(rs.next()) {
                
                Venda venda = new Venda(rs.getInt("codigo"),rs.getInt("id_produto"),
                        rs.getString("fornecedor"),rs.getInt("quantidade"));
                listaVendas.add(venda);
            }
            
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
        
        return listaVendas;
    }
    

    public void showJTable() {
        ArrayList<Venda> list = getVendasList(conn);
        DefaultTableModel model = (DefaultTableModel) jTableVenda.getModel();
        Object[] row = new Object[5];
        for (int i = 0; i < list.size(); i++) {
            row[0] = list.get(i).getCodigo();
            row[1] = list.get(i).getIdProduto();
            row[2] = list.get(i).getFornecedor();
            row[3] = list.get(i).getQuantidade();
            row[4] = list.get(i).getValorTotal();
                       
            model.addRow(row);
            
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTableVenda = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        jTableVenda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Id do Produto", "Fornecedor", "Quantidade"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTableVenda);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Relatório de Vendas");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addComponent(jLabel1)
                .addContainerGap(135, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableVenda;
    // End of variables declaration//GEN-END:variables
}
