/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Relatorios;

import Cadastro.Produto;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author juanfelipevillalba
 */
public class RelatoriosProdutosInternalFrame extends javax.swing.JInternalFrame {

    private final Connection conn;

    /**
     * Creates new form RelatoriosProdutosInternalFrame
     * @param conn
     */
    public RelatoriosProdutosInternalFrame(Connection conn) {
        initComponents();
        this.conn = conn;
        showJTable();
    }
    
    public ArrayList<Produto> getProdutosList(Connection conn) {
        ArrayList<Produto> listaProdutos = new ArrayList<>();
        
        String sql = "SELECT * FROM produto";

        
        try {
            
            Statement comandoSql = conn.createStatement();
            ResultSet rs  = comandoSql.executeQuery(sql);
            
            
            while(rs.next()) {
                
                Produto produto = new Produto(rs.getInt("codigo"),rs.getString("nome"),
                        rs.getString("fornecedor"),rs.getInt("preco"),rs.getInt("quantidade"));
                listaProdutos.add(produto);
            }
            
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
        
        return listaProdutos;
    }
    

    public void showJTable() {
        ArrayList<Produto> list = getProdutosList(conn);
        DefaultTableModel model = (DefaultTableModel) jTableProduto.getModel();
        Object[] row = new Object[5];
        for (int i = 0; i < list.size(); i++) {
            row[0] = list.get(i).getCodigo();
            row[1] = list.get(i).getNome();
            row[2] = list.get(i).getFornecedor();
            row[3] = list.get(i).getPreco();
            row[4] = list.get(i).getQuantidade();
                       
            model.addRow(row);
            
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableProduto = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        jTableProduto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cd. de Barras", "Nome", "Fornecedor", "Preço", "Quantidade"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableProduto);
        if (jTableProduto.getColumnModel().getColumnCount() > 0) {
            jTableProduto.getColumnModel().getColumn(0).setResizable(false);
            jTableProduto.getColumnModel().getColumn(1).setResizable(false);
        }

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Relatório de Produtos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addComponent(jLabel1)
                .addContainerGap(134, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(22, 22, 22)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableProduto;
    // End of variables declaration//GEN-END:variables
}
